[project]
name = "whisperx-server"
version = "0.1.0"
dependencies = [
    "fastapi==0.111.0",
    "uvicorn==0.30.0",
    "whisperx",
    "python-multipart==0.0.9",
    "faster-whisper>=1.0.3",
    "ctranslate2>=4.4.0",
    "pyannote.audio>=3.1.1",
]

[project.optional-dependencies]
cpu = ["torch>=2.3.0"]
cu121 = ["torch>=2.3.0"]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
